# Generated by Django 4.0.3 on 2025-11-20 08:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(help_text='کد ملی به عنوان شناسه یکتا برای مشتری', max_length=10, unique=True, verbose_name='کد ملی')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('birth_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد شمسی')),
                ('is_vip', models.BooleanField(default=False, verbose_name='مشتری ویژه')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ویژه')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='تعداد کل رزروها')),
                ('successful_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای موفق')),
                ('cancellation_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لغوها')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('created_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد شمسی')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_jalali'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه'), ('friday', 'جمعه')], max_length=20, unique=True, verbose_name='روز هفته')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='تعطیل آخر هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='ساعت شروع کار')),
                ('end_time', models.TimeField(default=datetime.time(23, 0), verbose_name='ساعت پایان کار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='شروع زمان استراحت')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='پایان زمان استراحت')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.workingday', verbose_name='روز هفته')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'زمان کاری',
                'verbose_name_plural': 'زمان\u200cهای کاری',
                'ordering': ['day__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50, verbose_name='شماره میز')),
                ('table_type', models.CharField(choices=[('standard', 'میز استاندارد'), ('booth', 'میز بوث'), ('bar', 'میز بار'), ('outdoor', 'میز فضای باز'), ('private', 'اتاق خصوصی'), ('family', 'میز فامیلی'), ('vip', 'میز وی\u200cآی\u200cپی')], default='standard', max_length=20, verbose_name='نوع میز')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='ظرفیت (تعداد نفر)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_reservation_duration', models.PositiveIntegerField(default=60, verbose_name='حداقل زمان رزرو (دقیقه)')),
                ('max_reservation_duration', models.PositiveIntegerField(default=240, verbose_name='حداکثر زمان رزرو (دقیقه)')),
                ('has_view', models.BooleanField(default=False, verbose_name='دارای ویو')),
                ('is_smoking', models.BooleanField(default=False, verbose_name='مجوز سیگار')),
                ('is_vip', models.BooleanField(default=False, verbose_name='میز وی\u200cآی\u200cپی')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='طبقه')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='بخش')),
                ('created_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد شمسی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
                'ordering': ['floor', 'table_number'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_advance_days', models.PositiveIntegerField(default=30, verbose_name='حداکثر روزهای پیش\u200cرو برای رزرو')),
                ('min_advance_hours', models.PositiveIntegerField(default=2, verbose_name='حداقل ساعت\u200cهای پیش\u200cرو برای رزرو')),
                ('max_guests_per_reservation', models.PositiveIntegerField(default=20, verbose_name='حداکثر تعداد مهمان در هر رزرو')),
                ('default_reservation_duration', models.PositiveIntegerField(default=120, verbose_name='مدت زمان پیش\u200cفرض رزرو (دقیقه)')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='مدت زمان هر اسلات (دقیقه)')),
                ('auto_confirm_reservations', models.BooleanField(default=False, verbose_name='تأیید خودکار رزروها')),
                ('require_phone_verification', models.BooleanField(default=True, verbose_name='نیاز به تأیید شماره تماس')),
                ('max_reservations_per_time_slot', models.PositiveIntegerField(default=1, verbose_name='حداکثر رزرو همزمان در هر اسلات')),
                ('allow_same_day_reservations', models.BooleanField(default=True, verbose_name='اجازه رزرو در همان روز')),
                ('friday_off', models.BooleanField(default=True, verbose_name='تعطیلی جمعه')),
                ('thursday_evening_off', models.BooleanField(default=False, verbose_name='تعطیلی پنجشنبه عصر')),
                ('special_holidays', models.TextField(blank=True, help_text='تاریخ\u200cهای تعطیل خاص (هر خط یک تاریخ شمسی - فرمت: YYYY/MM/DD)', verbose_name='تعطیلی\u200cهای خاص')),
                ('created_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد شمسی')),
                ('updated_jalali', models.CharField(blank=True, max_length=16, null=True, verbose_name='آخرین بروزرسانی شمسی')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_settings', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزروها',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=10, unique=True, verbose_name='کد رزرو')),
                ('reservation_jalali_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ رزرو شمسی')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد مهمان')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای ویژه')),
                ('reservation_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('seated', 'مشتری حاضر شد'), ('completed', 'اتمام یافته'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور')], default='pending', max_length=20, verbose_name='وضعیت رزرو')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmation_code', models.CharField(max_length=6, verbose_name='کد تأیید')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده با کد')),
                ('customer_arrived', models.BooleanField(default=False, verbose_name='مشتری حاضر شد')),
                ('arrival_jalali_time', models.CharField(blank=True, max_length=16, null=True, verbose_name='زمان حضور شمسی')),
                ('created_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد شمسی')),
                ('created_jalali_time', models.CharField(blank=True, max_length=8, null=True, verbose_name='ساعت ایجاد شمسی')),
                ('updated_jalali', models.CharField(blank=True, max_length=16, null=True, verbose_name='آخرین بروزرسانی شمسی')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='table.customer', verbose_name='مشتری')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='table.table', verbose_name='میز')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_jalali', '-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_code'], name='table_custo_nationa_323dde_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='table_custo_phone_n_5d3440_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_vip'], name='table_custo_is_vip_e19c55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together={('restaurant', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_code'], name='table_reser_reserva_301429_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_jalali_date'], name='table_reser_reserva_afa9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer'], name='table_reser_custome_40b2da_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_status'], name='table_reser_reserva_673207_idx'),
        ),
    ]
