# Generated by Django 4.0.3 on 2025-11-18 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_remove_restaurant_enabletablereservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه'), ('friday', 'جمعه')], max_length=20, unique=True, verbose_name='روز هفته')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50, verbose_name='شماره میز')),
                ('table_type', models.CharField(choices=[('standard', 'استاندارد'), ('booth', 'بخ'), ('bar', 'بار'), ('outdoor', 'فضای باز'), ('private', 'اتاق خصوصی')], default='standard', max_length=20, verbose_name='نوع میز')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='ظرفیت (تعداد نفر)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_reservation_duration', models.PositiveIntegerField(default=60, help_text='حداقل زمان رزرو به دقیقه', verbose_name='حداقل زمان رزرو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
                'ordering': ['table_number'],
                'unique_together': {('restaurant', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_advance_days', models.PositiveIntegerField(default=30, verbose_name='حداکثر روزهای پیش\u200cرو برای رزرو')),
                ('min_advance_hours', models.PositiveIntegerField(default=2, verbose_name='حداقل ساعت\u200cهای پیش\u200cرو برای رزرو')),
                ('max_guests_per_reservation', models.PositiveIntegerField(default=20, verbose_name='حداکثر تعداد مهمان در هر رزرو')),
                ('default_reservation_duration', models.PositiveIntegerField(default=120, verbose_name='مدت زمان پیش\u200cفرض رزرو (دقیقه)')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='مدت زمان هر اسلات (دقیقه)')),
                ('auto_confirm_reservations', models.BooleanField(default=False, verbose_name='تأیید خودکار رزروها')),
                ('require_phone_verification', models.BooleanField(default=True, verbose_name='نیاز به تأیید شماره تماس')),
                ('max_reservations_per_time_slot', models.PositiveIntegerField(default=1, verbose_name='حداکثر رزرو همزمان در هر اسلات')),
                ('allow_same_day_reservations', models.BooleanField(default=True, verbose_name='اجازه رزرو در همان روز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_settings', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزروها',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=10, unique=True, verbose_name='کد رزرو')),
                ('reservation_date', models.DateField(verbose_name='تاریخ رزرو')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('customer_full_name', models.CharField(max_length=255, verbose_name='نام کامل مشتری')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='شماره تماس مشتری')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای ویژه')),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد مهمان')),
                ('reservation_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('seated', 'مشتری حاضر شد'), ('completed', 'اتمام یافته'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور')], default='pending', max_length=20, verbose_name='وضعیت رزرو')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmation_code', models.CharField(max_length=6, verbose_name='کد تأیید')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده با کد')),
                ('customer_arrived', models.BooleanField(default=False, verbose_name='مشتری حاضر شد')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان حضور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='table.table', verbose_name='میز')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.workingday', verbose_name='روز هفته')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'زمان کاری',
                'verbose_name_plural': 'زمان\u200cهای کاری',
                'ordering': ['day__display_order', 'start_time'],
                'unique_together': {('restaurant', 'day')},
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_code'], name='table_reser_reserva_301429_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer_phone'], name='table_reser_custome_d967fd_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date', 'start_time'], name='table_reser_reserva_c368ab_idx'),
        ),
    ]
