# Generated by Django 4.0.3 on 2025-12-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_views', to='menu.restaurant', verbose_name='رستوران'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuCategories', to='menu.restaurant'),
        ),
        migrations.AddField(
            model_name='foodrestaurant',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_restaurants', to='menu.food', verbose_name='غذا'),
        ),
        migrations.AddField(
            model_name='foodrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to='menu.restaurant', verbose_name='رستوران'),
        ),
        migrations.AddField(
            model_name='food',
            name='menuCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.menucategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='foods', to='menu.restaurant', verbose_name='رستوران\u200cها'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.category'),
        ),
        migrations.AddIndex(
            model_name='menuview',
            index=models.Index(fields=['restaurant', 'created_at'], name='menu_menuvi_restaur_726959_idx'),
        ),
        migrations.AddIndex(
            model_name='menuview',
            index=models.Index(fields=['session_key', 'restaurant'], name='menu_menuvi_session_b194fb_idx'),
        ),
        migrations.AddIndex(
            model_name='menuview',
            index=models.Index(fields=['ip_address', 'restaurant'], name='menu_menuvi_ip_addr_e3fd47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuview',
            unique_together={('restaurant', 'session_key')},
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('restaurant', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='foodrestaurant',
            unique_together={('restaurant', 'food')},
        ),
    ]
