# Generated by Django 4.0.3 on 2025-12-24 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام طرح را وارد کنید', max_length=255, verbose_name='نام طرح')),
                ('design_file', models.FileField(help_text='فایل اصلی طرح را آپلود کنید', upload_to='designs/files/%Y/%m/%d/', verbose_name='فایل طرح')),
                ('preview', models.ImageField(blank=True, help_text='تصویر پیش\u200cنمایش طرح را آپلود کنید', null=True, upload_to='designs/previews/%Y/%m/%d/', verbose_name='پیش نمایش طرح')),
                ('html_file', models.FileField(blank=True, help_text='فایل HTML طرح را آپلود کنید', null=True, upload_to='designs/html/%Y/%m/%d/', verbose_name='فایل html طرح')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این طرح فعال است؟', verbose_name='فعال بودن')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='تاریخ ایجاد طرح', verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_style',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='theme',
        ),
    ]
