# Generated by Django 4.0.3 on 2025-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='enableTableReservation',
            field=models.BooleanField(default=False, verbose_name='فعالسازی رزرو میز'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='maxGuestsPerReservation',
            field=models.PositiveIntegerField(default=10, verbose_name='حداکثر تعداد مهمان در هر رزرو'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='minReservationAdvanceHours',
            field=models.PositiveIntegerField(default=2, verbose_name='حداقل ساعت پیش\u200cرو برای رزرو'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservationAdvanceDays',
            field=models.PositiveIntegerField(default=30, verbose_name='حداکثر روزهای پیش\u200cرو برای رزرو'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservationInstructions',
            field=models.TextField(blank=True, null=True, verbose_name='دستورالعمل\u200cهای رزرو'),
        ),
    ]
