# Generated by Django 4.0.3 on 2025-11-23 14:25

import apps.menu.models.menufreemodels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['displayOrder'], 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AddField(
            model_name='food',
            name='allow_description_change',
            field=models.BooleanField(default=False, verbose_name='اجازه تغییر توضیحات'),
        ),
        migrations.AddField(
            model_name='food',
            name='allow_image_change',
            field=models.BooleanField(default=False, verbose_name='اجازه تغییر تصویر'),
        ),
        migrations.AddField(
            model_name='food',
            name='allow_preparation_time_change',
            field=models.BooleanField(default=False, verbose_name='اجازه تغییر زمان آماده\u200cسازی'),
        ),
        migrations.AddField(
            model_name='food',
            name='allow_price_change',
            field=models.BooleanField(default=False, verbose_name='اجازه تغییر قیمت'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_customizable',
            field=models.BooleanField(default=False, verbose_name='قابل تنظیم توسط رستوران'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_image, verbose_name='تصویر پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparationTime',
            field=models.IntegerField(blank=True, help_text='زمان آماده\u200cسازی پایه (دقیقه)', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پایه (تومان)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price_usd_cents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پایه (سنت)'),
        ),
        migrations.CreateModel(
            name='RestaurantFoodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_image, verbose_name='تصویر سفارشی')),
                ('custom_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت سفارشی (تومان)')),
                ('custom_price_usd_cents', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت سفارشی (سنت)')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سفارشی فارسی')),
                ('custom_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات سفارشی انگلیسی')),
                ('custom_preparation_time', models.IntegerField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی سفارشی (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_customizations', to='menu.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_foods', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Food Customization',
                'verbose_name_plural': 'Restaurant Food Customizations',
                'ordering': ['-created_at'],
                'unique_together': {('restaurant', 'food')},
            },
        ),
    ]
