# Generated by Django 5.1.1 on 2025-11-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='کلید سشن')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_views', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'بازدید منو',
                'verbose_name_plural': 'بازدیدهای منو',
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='menu_menuvi_restaur_726959_idx'), models.Index(fields=['session_key', 'restaurant'], name='menu_menuvi_session_b194fb_idx'), models.Index(fields=['ip_address', 'restaurant'], name='menu_menuvi_ip_addr_e3fd47_idx')],
                'unique_together': {('restaurant', 'session_key')},
            },
        ),
    ]
