# Generated by Django 4.0.3 on 2025-12-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_design_remove_restaurant_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.design', verbose_name='طرح منو کاغذی'),
        ),
    ]
