# Generated by Django 4.0.3 on 2025-11-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_restaurant_enabletablereservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='enableTableReservation',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='maxGuestsPerReservation',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='minReservationAdvanceHours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reservationAdvanceDays',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reservationInstructions',
        ),
    ]
