# Generated by Django 4.0.3 on 2025-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background_color',
            field=models.CharField(default='#F9FAFB', max_length=7, verbose_name='رنگ پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_active',
            field=models.BooleanField(default=True, verbose_name='منو فعال'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_style',
            field=models.CharField(choices=[('grid', 'شبکه\u200cای'), ('list', 'لیستی'), ('compact', 'فشرده')], default='grid', max_length=10, verbose_name='سبک منو'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(default='#10B981', max_length=7, verbose_name='رنگ ثانویه'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_preparation_time',
            field=models.BooleanField(default=True, verbose_name='نمایش زمان آماده\u200cسازی'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_usd_price',
            field=models.BooleanField(default=False, verbose_name='نمایش قیمت دلار'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='text_color',
            field=models.CharField(default='#1F2937', max_length=7, verbose_name='رنگ متن'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(choices=[('light', 'روشن'), ('dark', 'تیره'), ('auto', 'خودکار')], default='auto', max_length=10, verbose_name='تم'),
        ),
    ]
