# Generated by Django 4.0.3 on 2025-11-23 14:49

import apps.menu.models.menufreemodels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_food_options_food_allow_description_change_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['displayOrder']},
        ),
        migrations.RemoveField(
            model_name='food',
            name='allow_description_change',
        ),
        migrations.RemoveField(
            model_name='food',
            name='allow_image_change',
        ),
        migrations.RemoveField(
            model_name='food',
            name='allow_preparation_time_change',
        ),
        migrations.RemoveField(
            model_name='food',
            name='allow_price_change',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_customizable',
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_image),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparationTime',
            field=models.IntegerField(blank=True, help_text='زمان آماده\u200cسازی (دقیقه)', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price_usd_cents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (سنت)'),
        ),
        migrations.DeleteModel(
            name='RestaurantFoodCustomization',
        ),
    ]
