# Generated by Django 4.0.3 on 2025-11-23 16:17

import apps.menu.models.menufreemodels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_food_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کاستوم (تومان)')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_restaurant_image, verbose_name='عکس کاستوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_restaurants', to='menu.food', verbose_name='غذا')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_restaurants', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'غذای کاستوم رستوران',
                'verbose_name_plural': 'غذاهای کاستوم رستوران',
                'db_table': 'restaurant_food_restaurant',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('restaurant', 'food')},
            },
        ),
    ]
