# Generated by Django 4.0.3 on 2025-12-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='design',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
