# Generated by Django 4.0.3 on 2025-12-24 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_restaurant_design_delete_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPaperDesien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان طرخ')),
                ('isActive', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='RequestToCreatePaperMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='متن محتوا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('delivered', 'تحویل شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('background_image', models.ImageField(blank=True, help_text='تصویر زمینه منو را آپلود کنید', null=True, upload_to='paper_menu_backgrounds/', verbose_name='عکس بک\u200cگراند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menupaperdesien', verbose_name='طرح منو')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'درخواست ایجاد منو کاغذی',
                'verbose_name_plural': 'درخواست\u200cهای ایجاد منو کاغذی',
            },
        ),
    ]
