# Generated by Django 4.0.3 on 2025-11-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_foodrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrestaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodrestaurant',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_restaurants', to='menu.food', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='foodrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to='menu.restaurant', verbose_name='رستوران'),
        ),
    ]
