# Generated by Django 4.0.3 on 2025-12-24 16:12

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menupaperdesien_requesttocreatepapermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupaperdesien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
