# Generated by Django 4.0.3 on 2025-12-31 07:49

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menupaperdesien_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupaperdesien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
