# Generated by Django 4.0.3 on 2026-01-28 13:35

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menupaperdesien_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='freeSmoke',
            field=models.BooleanField(default=False, verbose_name='ازادی سیگار'),
        ),
        migrations.AlterField(
            model_name='menupaperdesien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
