# Generated by Django 4.0.3 on 2025-12-23 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='تلفن تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('codePost', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی سفارش',
                'verbose_name_plural': 'اطلاعات تکمیلی سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='عکس')),
                ('alt_text', models.CharField(max_length=200, verbose_name='متن جایگزین')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'عکس گالری',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='قیمت کل (بدون مالیات)')),
                ('tax_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ مالیات ۹٪')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی (با مالیات)')),
                ('isPaid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paidAt', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('trackingCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('expiryDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='plan.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'سفارش محصول',
                'verbose_name_plural': 'سفارشات محصول',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام محصول')),
                ('product_description', models.TextField(blank=True, verbose_name='توضیحات محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productorder', verbose_name='سفارش محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش محصول',
                'verbose_name_plural': 'جزئیات سفارشات محصول',
            },
        ),
    ]
