# Generated by Django 4.0.3 on 2025-11-20 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='product_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='product.productorder', verbose_name='سفارش محصول'),
        ),
        migrations.AlterUniqueTogether(
            name='productorderdetail',
            unique_together={('product_order', 'product')},
        ),
    ]
