# Generated by Django 4.0.3 on 2025-12-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='productorder',
            name='plan_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پلن'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='products_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت محصولات'),
        ),
    ]
