# Generated by Django 4.0.3 on 2025-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ مالیات ۹٪'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی (با مالیات)'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کل (بدون مالیات)'),
        ),
    ]
