# Generated by Django 4.0.3 on 2025-12-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productorder_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='plan_price',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='products_price',
        ),
        migrations.AddField(
            model_name='productorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کل (بدون مالیات)'),
        ),
    ]
