# Generated by Django 4.0.3 on 2025-11-27 12:45

import apps.user.validators.mobile_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد گارسون')),
                ('mobileNumber', models.CharField(max_length=11, validators=[apps.user.validators.mobile_validator.validate_iranian_mobile], verbose_name='شماره موبایل')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'گارسون',
                'verbose_name_plural': 'گارسون\u200cها',
                'ordering': ['-createdAt'],
                'unique_together': {('restaurant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('custom_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کاستوم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='برای شناسایی مشتری بدون نیاز به لاگین', max_length=255, verbose_name='کلید سشن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('served', 'سرو شده'), ('cancelled', 'لغو شده'), ('paid', 'پرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='قیمت کل')),
                ('tax_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ مالیات')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی')),
                ('table_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره میز')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مشتری')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان سرو')),
                ('items', models.ManyToManyField(related_name='orders', to='waiter.orderitem', verbose_name='آیتم\u200cهای سفارش')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.restaurant', verbose_name='رستوران')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='waiter.waiter', verbose_name='گارسون')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='WaiterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='waiter.order', verbose_name='سفارش')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='waiter.waiter', verbose_name='گارسون')),
            ],
            options={
                'verbose_name': 'انتساب گارسون',
                'verbose_name_plural': 'انتساب\u200cهای گارسون',
                'ordering': ['-assigned_at'],
                'unique_together': {('waiter', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session_key', 'restaurant'], name='waiter_orde_session_88b358_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'createdAt'], name='waiter_orde_status_400449_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter', 'status'], name='waiter_orde_waiter__dc3250_idx'),
        ),
    ]
