# Generated by Django 4.0.3 on 2025-11-27 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(verbose_name='توضیحات پرداخت')),
                ('isFinaly', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('statusCode', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت پرداخت')),
                ('refId', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
                ('payment_type', models.CharField(choices=[('menu', 'منو'), ('plan', 'پلن'), ('product', 'محصول')], default='menu', max_length=20, verbose_name='نوع پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('plan_order_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه سفارش پلن')),
                ('product_order_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه سفارش محصول')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
