# Generated by Django 4.0.3 on 2025-11-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermenu_image'),
        ('peyment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyment',
            name='payment_type',
            field=models.CharField(choices=[('menu', 'منو'), ('plan', 'پلن'), ('product', 'محصول')], default='menu', max_length=20, verbose_name='نوع پرداخت'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='plan_order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه سفارش پلن'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='product_order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه سفارش محصول'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='peyment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peyment_order', to='order.ordermenu', verbose_name='سفارش منو'),
        ),
    ]
