# Generated by Django 4.0.3 on 2025-11-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
