# Generated by Django 4.0.3 on 2025-12-23 16:01

import ckeditor_uploader.fields
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتواها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('image', models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
                ('image_position', models.CharField(choices=[('left', 'تصویر در چپ'), ('right', 'تصویر در راست')], default='right', max_length=5, verbose_name='موقعیت تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'باکس متن و تصویر',
                'verbose_name_plural': 'باکس\u200cهای متن و تصویر',
                'ordering': ['order'],
            },
        ),
    ]
