# Generated by Django 5.1.1 on 2025-11-28 10:30

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimageblock',
            name='image',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
