# Generated by Django 5.1.1 on 2025-12-01 08:05

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_textimageblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتواها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='textimageblock',
            name='image',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
