# Generated by Django 4.0.3 on 2025-12-31 12:08

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_textimageblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان دوره آموزشی', max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(help_text='توضیحات کامل دوره', verbose_name='توضیحات')),
                ('video_link', models.URLField(blank=True, help_text='لینک ویدیو آموزشی', max_length=500, null=True, verbose_name='لینک ویدیو')),
                ('is_active', models.BooleanField(default=True, help_text='آیا دوره فعال است؟', verbose_name='فعال')),
                ('thumbnail', models.ImageField(blank=True, default='courses/default_thumbnail.jpg', help_text='تصویر شاخص دوره', upload_to='courses/thumbnails/', verbose_name='عکس پیش فرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='textimageblock',
            name='image',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
